### ISSUE TITLE
Back button history support

### ISSUE THREAD

**Issue by GrandFelix** [maxches99/SwiftUI-MVVM-C#1]
Hi,

how do you solve back button hierarchy that iOS supports it by default (when you hold back button for some time you get all history to the root view). Like [here](https://ibb.co/0B6BF3g)

**Comment by maxches99** [comment]
> Hi,
> 
> how do you solve back button hierarchy that iOS supports it by default (when you hold back button for some time you get all history to the root view). Like [here](https://ibb.co/0B6BF3g)

Hey! It's a very interesting question and an interesting mechanic. I will try to make this mechanic in the near future.

**Comment by GrandFelix** [comment]
Also, is this approach compatible with iPadOS where there is main view and detail view. So when you push a view its in detail view etc. ? Im asking this because like your approach but it is missing some major swiftui implementations..

**Comment by maxches99** [comment]
> Also, is this approach compatible with iPadOS where there is main view and detail view. So when you push a view its in detail view etc. ? Im asking this because like your approach but it is missing some major swiftui implementations..

Regarding the question about iPads, you can have multiple views and models in the same scene/coordinator and then show them in the NavigationView or make the navigation stack style.

**Comment by GrandFelix** [comment]
Thank you!
